[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
auto_detect_solc = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# allow the beta distribution json file to be read during script execution
fs_permissions = [
  { access = "read-write", path = "./script" }
]
